### ISSUE TITLE
After reloade stop work -  BUG FOUND [BUG]

### ISSUE THREAD

**Issue by Dark3n89** [facebook-adblock/facebook_adblock#112]
Hi, I tried to solve the problem myself but I can't, as many have reported, the script really stops working. IT WILL HAPPEN WHEN THE USER CLICKS ON THE FACEBOOK LOGO TO RETURN TO THE MAIN PAGE. The cause will be somewhere around `console.info("Monitoring feed updates", [feed]);`, a message will be displayed and the script will stop.

**Comment by cbotsikas** [comment]
Thank you for reporting. I was able to reproduce and find the issue.

**Comment by Dark3n89** [comment]
@cbotsikas  I solve problem, after delete `feedObserver.disconnect();`   ( example inside picture: [https://i.ibb.co/kccScQw/image.png](url) )  This problem is gone and script continue deleting again.

**Comment by cbotsikas** [comment]
@Dark3n89 I already have a working solution but we haven't released a new version yet. You need to disconnect to prevent memory leak. If you see the last commit, I'm cleaning up in case you come back to home screen.

**Comment by tiratatp** [comment]
Fixed in v1.9.7
